# Generated by Django 3.2 on 2023-04-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='url_video',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube URL'),
        ),
    ]
