# Generated by Django 3.2 on 2023-04-12 23:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(verbose_name='URL')),
                ('q', models.CharField(max_length=100, verbose_name='Parámetros de Busqueda')),
                ('lang', models.CharField(choices=[('', 'Todos'), ('es', 'Español'), ('en', 'Ingles'), ('fr', 'Frances'), ('it', 'Italiano'), ('ja', 'Japones')], max_length=2, verbose_name='Idioma de Noticias')),
                ('country', models.CharField(choices=[('', 'Todos'), ('mx', 'México'), ('us', 'Estados Unidos'), ('es', 'España'), ('fr', 'Francia'), ('gb', 'Reino Unido'), ('it', 'Italia'), ('jp', 'Japón')], max_length=2, verbose_name='País de Noticias')),
                ('category', models.CharField(choices=[('', 'Todos'), ('news', 'Noticias'), ('sport', 'Deportes'), ('tech', 'Tecnologia'), ('world', 'Mundo'), ('finance', 'Finanzas'), ('politics', 'Politica'), ('business', 'Negocios'), ('economics', 'Economia'), ('entertainment', 'Entretenimiento'), ('beauty', 'Belleza'), ('travel', 'Travel'), ('travel', 'Viajes'), ('music', 'Musica'), ('food', 'Comida'), ('science', 'Ciencia'), ('gaming', 'Videojuegos'), ('energy', 'Energia')], max_length=20, verbose_name='Tópicos de Noticias')),
                ('sources', models.CharField(max_length=100, verbose_name='Fuentes de Noticias')),
                ('pageSize', models.IntegerField(verbose_name='Articulos por Pagina')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
            },
        ),
    ]
