# Generated by Django 3.2 on 2023-04-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='sources',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fuentes de Noticias'),
        ),
    ]
