# Generated by Django 3.2 on 2023-04-22 23:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App_New',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(max_length=100, verbose_name='Titular')),
                ('subtitle', models.TextField(verbose_name='Resumen')),
                ('body', models.TextField(verbose_name='Cuerpo')),
                ('image_news', models.ImageField(upload_to='', verbose_name='Imagen Noticia')),
                ('url_news', models.URLField(verbose_name='URL Noticia')),
                ('source', models.CharField(max_length=100, verbose_name='Fuente')),
                ('author', models.CharField(default='Agencias', max_length=100, verbose_name='Autor')),
                ('date_news', models.DateField(verbose_name='Fecha de Publicación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
            },
        ),
    ]
