# Generated by Django 3.2 on 2023-04-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_new',
            name='author',
            field=models.CharField(default='Agencias', max_length=700, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='app_new',
            name='body',
            field=models.TextField(max_length=300, verbose_name='Cuerpo'),
        ),
        migrations.AlterField(
            model_name='app_new',
            name='date_news',
            field=models.DateField(max_length=800, verbose_name='Fecha de Publicación'),
        ),
        migrations.AlterField(
            model_name='app_new',
            name='image_news',
            field=models.ImageField(max_length=400, upload_to='', verbose_name='Imagen Noticia'),
        ),
        migrations.AlterField(
            model_name='app_new',
            name='source',
            field=models.CharField(max_length=600, verbose_name='Fuente'),
        ),
        migrations.AlterField(
            model_name='app_new',
            name='subtitle',
            field=models.TextField(max_length=200, verbose_name='Resumen'),
        ),
        migrations.AlterField(
            model_name='app_new',
            name='url_news',
            field=models.URLField(max_length=500, verbose_name='URL Noticia'),
        ),
    ]
