# Generated by Django 3.2 on 2023-04-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_auto_20230422_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_new',
            name='author',
            field=models.CharField(default='Agencias', max_length=100, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='app_new',
            name='body',
            field=models.TextField(verbose_name='Cuerpo'),
        ),
        migrations.AlterField(
            model_name='app_new',
            name='date_news',
            field=models.DateField(verbose_name='Fecha de Publicación'),
        ),
        migrations.AlterField(
            model_name='app_new',
            name='image_news',
            field=models.ImageField(upload_to='', verbose_name='Imagen Noticia'),
        ),
        migrations.AlterField(
            model_name='app_new',
            name='source',
            field=models.CharField(max_length=100, verbose_name='Fuente'),
        ),
        migrations.AlterField(
            model_name='app_new',
            name='subtitle',
            field=models.TextField(verbose_name='Resumen'),
        ),
        migrations.AlterField(
            model_name='app_new',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titular'),
        ),
        migrations.AlterField(
            model_name='app_new',
            name='url_news',
            field=models.URLField(max_length=400, verbose_name='URL Noticia'),
        ),
    ]
