# Generated by Django 3.2 on 2023-04-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_auto_20230422_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_new',
            name='image_news',
            field=models.ImageField(max_length=400, upload_to='', verbose_name='Imagen Noticia'),
        ),
    ]
