# Generated by Django 3.2 on 2023-04-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0004_alter_app_new_image_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_new',
            name='body',
            field=models.TextField(max_length=300, verbose_name='Cuerpo'),
        ),
    ]
