# Generated by Django 3.2 on 2023-04-12 23:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('headline', models.CharField(max_length=40, verbose_name='Nombre')),
                ('lead', models.CharField(max_length=40, verbose_name='Frase')),
                ('body', models.TextField(max_length=100, verbose_name='Resumen')),
                ('url_video', models.URLField(verbose_name='Youtube URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
            },
        ),
    ]
