# Generated by Django 3.2 on 2023-04-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_rename_testimonials_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image_testimonial',
            field=models.ImageField(default='default.jpg', upload_to='', verbose_name='Imagen Testimonio'),
        ),
    ]
